sudo: false

language: python

python:
  - "3.5"

env:
  - TOXENV=py27-django17,py33-django17
  - TOXENV=py27-django18,py33-django18
  - TOXENV=py27-django19,py34-django19
  - TOXENV=py27-django110,py35-django110
  - TOXENV=py27-django111,py35-django111

matrix:
  allow_failures:
    - env: TOXENV=py27-django111,py35-django111

install:
  - pip install tox pip wheel codecov -U

script:
  - tox

after_success:
  - codecov -e TOX_ENV

branches:
  only:
    - master
